baseURL = 'https://txt.felipe.cloud'
languageCode = 'en-us'
title = 'Tech Pills'
theme = "yinyang"
canonifyURLs = false
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2



[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English ðŸ‡¬ðŸ‡§"
    weight = 1
  [languages.pt]
    contentDir = "content/pt"
    languageName = "Portuguese ðŸ‡§ðŸ‡·"
    weight = 2

[permalinks]
post = "/blog/:title/"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'


[params]
  mainSections = ["posts"]
  headTitle = "Tech Pills"
  description = "Sharing what made me smarter." 
  favicon = "/logo.png" 

  [[params.meta]]
  favicon = true


[[params.author]]
    name = "Felipe A."
    homepage = "https://hello.felipe.cloud"


[[params.socials]]
link = "https://hello.felipe.cloud"
name = "About"

postHeaderContent = ""
postFooterContent = ""